# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '$(System.DefaultWorkingDirectory)/_amrabunemr98_Task/MySQL-and-Python/FlaskApp/Dockerfile'
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'Task..'
        regionName: 'us-east-1'
        imageSource: 'imageid'
        sourceImageId: '$(imageName):$(Build.BuildId)'
        repositoryName: '$(repoName)'
        pushTag: '$(imageName)'