# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/MySQL-and-Python/FlaskApp/Dockerfile'
        tags: |
          $(tag)
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'Task.'
        regionName: 'us-east-1'
        imageSource: 'imageid'
        sourceImageId: 'flask-app:$(Build.BuildId)'
        repositoryName: 'task-ecr-repo'
        forceDockerNamingConventions: true